---
- name: Pull and Run Docker Container of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
      become: yes  # If sudo permissions are required

    - name: Pull Docker image
      docker_image:
        name: rajb957/calculator:latest
        source: pull

    - name: Run Calculator container
      docker_container:
        name: Calculator
        image: rajb957/calculator:latest
        state: started
        detach: true
        tty: true
