---
- name: Pull Docker Image of Calculator
  hosts: ['localhost']
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: rajb957/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Delete container if already running
      shell: docker rm -f Calculator
      ignore_errors: yes
    - name: Running container
      shell: docker run -it -d --name Calculator rajb957/calculator